path: 
  train_path: './data/ground_truth_train.csv'
  test_path: './data/ground_truth_test.csv'
  output_dir: './data/processed'

trainer:
  num_train_epochs: 1
  learning_rate: 8.521786512851659e-05
  train_batch_size: 8
  eval_batch_size: 24
  max_seq_length: 512
  output_dir: "outputs/"
  overwrite_output_dir: True
  device: "cuda"
  use_kfold: False
  n_splits: 5